namespace BG3ItemExplorer;

internal enum UiLanguage
{
    English,
    Dutch
}

internal static class Localization
{
    public static UiLanguage Current { get; set; } = UiLanguage.English;

    private static readonly Dictionary<string, (string English, string Dutch)> Texts = new()
    {
        ["Subtitle"] = ("Acts 1, 2 & 3 • offline • complete item information • data & images: bg3.wiki", "Act 1, 2 & 3 • offline • volledige iteminformatie • data & afbeeldingen: bg3.wiki"),
        ["FiltersTitle"] = ("SEARCH & FILTER", "ZOEKEN & FILTEREN"),
        ["Language"] = ("Language", "Taal"),
        ["SearchAll"] = ("Search all fields", "Zoek in alle velden"),
        ["SearchPlaceholder"] = ("Name, effect, location...", "Naam, effect, locatie..."),
        ["Acts"] = ("Acts", "Acts"),
        ["Rarity"] = ("Rarity", "Zeldzaamheid"),
        ["Type"] = ("Type", "Type"),
        ["AllTypes"] = ("All types", "Alle types"),
        ["Place"] = ("Area or location", "Gebied of locatie"),
        ["AllPlaces"] = ("All areas/locations", "Alle gebieden/locaties"),
        ["NotesOnly"] = ("Only items with a note", "Alleen items met een notitie"),
        ["EquippedOnly"] = ("Equipped only (active template)", "Alleen gedragen (actieve template)"),
        ["Progress"] = ("Progress", "Voortgang"),
        ["AllItems"] = ("All items", "Alle items"),
        ["NotFound"] = ("Still needed", "Nog zoeken"),
        ["Found"] = ("Found", "Gevonden"),
        ["Sorting"] = ("Sort", "Sorteren"),
        ["SortName"] = ("Name", "Naam"),
        ["SortRarity"] = ("Rarity", "Zeldzaamheid"),
        ["SortType"] = ("Type", "Type"),
        ["SortAct"] = ("Act", "Act"),
        ["SortLocation"] = ("Location", "Locatie"),
        ["SortStatus"] = ("Status", "Status"),
        ["Ascending"] = ("A → Z", "A → Z"),
        ["Descending"] = ("Z → A", "Z → A"),
        ["Reset"] = ("Clear filters", "Filters wissen"),
        ["ResultCount"] = ("{0:N0} visible • {1:N0}/{2:N0} found", "{0:N0} zichtbaar • {1:N0}/{2:N0} gevonden"),
        ["NoItems"] = ("No items found", "Geen items gevonden"),
        ["AdjustFilters"] = ("Adjust the filters to show results.", "Pas de filters aan om resultaten te tonen."),
        ["GridFound"] = ("✓", "✓"),
        ["FoundTooltip"] = ("Found / collected", "Gevonden / opgehaald"),
        ["GridEquipped"] = ("⚔", "⚔"),
        ["EquippedTooltip"] = ("Equipped on character", "Gedragen door personage"),
        ["EquippedTemplateTooltip"] = ("Equip for template {0}: {1}", "Uitrusten voor template {0}: {1}"),
        ["GridName"] = ("Name", "Naam"),
        ["GridRarity"] = ("Rarity", "Zeldzaamheid"),
        ["GridType"] = ("Type", "Type"),
        ["GridProperties"] = ("Properties", "Eigenschappen"),
        ["GridActArea"] = ("Act Area", "Actgebied"),
        ["GridLocation"] = ("Location", "Locatie"),
        ["GridDescription"] = ("Description", "Beschrijving"),
        ["GridNotes"] = ("Notes", "Notities"),
        ["Properties"] = ("PROPERTIES", "EIGENSCHAPPEN"),
        ["ActArea"] = ("ACT AREA", "ACTGEBIED"),
        ["Location"] = ("LOCATION", "LOCATIE"),
        ["Description"] = ("DESCRIPTION", "BESCHRIJVING"),
        ["Notes"] = ("NOTES", "NOTITIES"),
        ["MarkFound"] = ("Mark as found", "Markeer als gevonden"),
        ["FoundButton"] = ("✓ Found", "✓ Gevonden"),
        ["OpenLink"] = ("Open {0}", "Open {0}"),
        ["NoLink"] = ("No external source link for this item.", "Geen externe bronlink voor dit item."),
        ["Source"] = ("Data & images: bg3.wiki", "Data & afbeeldingen: bg3.wiki"),
        ["Footer"] = ("Non-commercial fan tool • progress is saved next to the exe", "Niet-commerciële fan-tool • voortgang wordt naast de exe opgeslagen"),
        ["ProgressError"] = ("Progress could not be saved next to the exe. Check whether the USB folder is writable.\n\n{0}", "De voortgang kon niet naast de exe worden opgeslagen. Controleer of de USB-map schrijfbaar is.\n\n{0}"),
        ["LinkError"] = ("The link could not be opened.\n\n{0}", "De link kon niet worden geopend.\n\n{0}"),
        ["LoadError"] = ("BG3 Item Explorer encountered an unexpected error.\n\n{0}\n\nDiagnostic log: {1}", "BG3 Item Explorer kreeg een onverwachte fout.\n\n{0}\n\nDiagnostisch logboek: {1}"),
        ["WarningTitle"] = ("BG3 Item Explorer", "BG3 Item Explorer"),
        ["CharacterSheet"] = ("CHARACTER SHEET", "CHARACTER SHEET"),
        ["CharacterTemplate"] = ("Template", "Template"),
        ["CharacterName"] = ("Character name", "Naam personage"),
        ["ShareId"] = ("SHAREABLE TEMPLATE ID", "DEELBARE TEMPLATE-ID"),
        ["CopyLink"] = ("Copy link", "Kopieer link"),
        ["Copied"] = ("Copied", "Gekopieerd"),
        ["Import"] = ("Import", "Importeer"),
        ["ImportTemplate"] = ("Import character template", "Personagetemplate importeren"),
        ["PasteShareId"] = ("Paste a BG3T1 template ID or its complete share link:", "Plak een BG3T1-template-ID of de volledige deellink:"),
        ["Cancel"] = ("Cancel", "Annuleren"),
        ["ImportSuccess"] = ("The template and its equipped gear were imported.", "De template en de gedragen uitrusting zijn geïmporteerd."),
        ["ImportError"] = ("This template could not be imported.\n\n{0}", "Deze template kon niet worden geïmporteerd.\n\n{0}"),
        ["ShareCopyError"] = ("The share link could not be copied.\n\n{0}", "De deellink kon niet worden gekopieerd.\n\n{0}"),
        ["StatsTab"] = ("STATS", "STATS"),
        ["BuildTab"] = ("BUILD", "BUILD"),
        ["Identity"] = ("BUILD", "BUILD"),
        ["Race"] = ("Race", "Ras"),
        ["Class"] = ("Class", "Klasse"),
        ["Level"] = ("Level", "Level"),
        ["StartClass"] = ("Starting class", "Startklasse"),
        ["MainSubclass"] = ("Main-class subclass", "Subclass van de hoofdklasse"),
        ["SubclassAtLevel"] = ("Subclass unlocks at class level {0}", "Subclass komt vrij op class level {0}"),
        ["TotalLevel"] = ("Total level", "Totaal level"),
        ["ClassLevels"] = ("CLASS LEVELS (MAX 12)", "CLASS LEVELS (MAX. 12)"),
        ["ClassFeatures"] = ("CLASS FEATURES & FIGHTING STYLES", "CLASS FEATURES & FIGHTING STYLES"),
        ["Feats"] = ("FEATS", "FEATS"),
        ["FeatSlots"] = ("Available feat slots: {0}. Fighters also gain one at class level 6; Rogues at 10.", "Beschikbare feat-slots: {0}. Fighters krijgen er ook één op class level 6; Rogues op 10."),
        ["ActiveSpellsConditions"] = ("ACTIVE SPELLS & CONDITIONS  ([C] = CONCENTRATION)", "ACTIEVE SPELLS & CONDITIONS  ([C] = CONCENTRATION)"),
        ["ClassSubclassOptions"] = ("MAIN CLASS & SUBCLASS OPTIONS", "HOOFDKLASSE- & SUBCLASSOPTIES"),
        ["NoClassOptions"] = ("No modelled toggleable options at this class level.", "Geen gemodelleerde aanvinkopties op dit class level."),
        ["PermanentBonuses"] = ("PERMANENT BONUSES", "PERMANENTE BONUSSEN"),
        ["ClassLevelSummary"] = ("Total: {0}/{1}. Starting class determines saving-throw proficiencies.", "Totaal: {0}/{1}. De startklasse bepaalt saving-throw proficiencies."),
        ["ExplorerMulticlassDisabled"] = ("Explorer disables multiclassing.", "Explorer schakelt multiclassing uit."),
        ["Difficulty"] = ("Difficulty", "Moeilijkheid"),
        ["DifficultyExplorer"] = ("Explorer: party HP ×2; every creature gets +2 proficiency; no multiclassing.", "Explorer: party-HP ×2; elk wezen krijgt +2 proficiency; geen multiclassing."),
        ["DifficultyBalanced"] = ("Balanced: standard rules and baseline values.", "Balanced: standaardregels en baselinewaarden."),
        ["DifficultyTactician"] = ("Tactician: enemies gain +2 attack and save DC; tougher tactics; long rest costs 80 supplies.", "Tactician: vijanden krijgen +2 attack en save DC; betere tactieken; long rest kost 80 supplies."),
        ["DifficultyHonour"] = ("Honour: Tactician combat bonuses plus Legendary Actions and a single-save campaign.", "Honour: Tactician-combatbonussen plus Legendary Actions en één savebestand."),
        ["BaseAbilities"] = ("LEVEL 1 ABILITY SCORES", "ABILITY SCORES OP LEVEL 1"),
        ["Offense"] = ("OFFENSE", "AANVAL"),
        ["Defense"] = ("DEFENSE", "VERDEDIGING"),
        ["EnemyHitChance"] = ("ENEMY SUCCESS CHANCE", "KANS DAT VIJAND SLAAGT"),
        ["CharacterHitChance"] = ("CHARACTER SUCCESS CHANCE", "KANS DAT PERSONAGE SLAAGT"),
        ["EquippedGear"] = ("EQUIPPED GEAR", "GEDRAGEN UITRUSTING"),
        ["ActiveConditions"] = ("ACTIVE CONDITIONAL EFFECTS", "ACTIEVE VOORWAARDELIJKE EFFECTEN"),
        ["BenchmarkNote"] = ("Every spell or action specifies its own STR, DEX, CON, INT, WIS or CHA save. All six chances are therefore shown separately. Left: chance the enemy attack/effect succeeds against you. Right: chance your attack/effect succeeds against the benchmark target. Immunities and damage resistances are not part of the save percentage.", "Elke spell of action bepaalt zelf een STR-, DEX-, CON-, INT-, WIS- of CHA-save. Daarom worden alle zes kansen afzonderlijk getoond. Links: kans dat de vijandelijke attack/het effect tegen jou slaagt. Rechts: kans dat jouw attack/het effect tegen het benchmarkdoel slaagt. Immuniteiten en damage resistances zitten niet in het savepercentage."),
        ["OffenseLine"] = ("Weapon {0} ({1}) • Best spell attack {2} ({3}, {4}) • Proficiency +{5}", "Wapen {0} ({1}) • Beste spell attack {2} ({3}, {4}) • Proficiency +{5}"),
        ["DefenseLine"] = ("HP {0} • Initiative {1} • Movement {2:0.#} m", "HP {0} • Initiative {1} • Beweging {2:0.#} m"),
        ["SavingThrows"] = ("Saving throws", "Saving throws"),
        ["WorstCase"] = ("WORST CASE", "STERKSTE VIJAND"),
        ["Average"] = ("AVERAGE", "GEMIDDELDE"),
        ["ThreatLine"] = ("Attack {0}% — {1} +{2}\nSpell attack {3}% — {4} +{5}\nSpell effect {6}% — DC {7} vs {8}", "Attack {0}% — {1} +{2}\nSpell attack {3}% — {4} +{5}\nSpell effect {6}% — DC {7} vs {8}"),
        ["EnemyThreatLine"] = ("Attack {0}% — {1} +{2}\nSpell attack {3}% — {4} +{5}\nSpell effects — DC {6}\n{7}", "Attack {0}% — {1} +{2}\nSpell attack {3}% — {4} +{5}\nSpell effects — DC {6}\n{7}"),
        ["CharacterThreatLine"] = ("Weapon {0}% — {1}, AC {2}\nSpell attack {3}% — AC {4}\nSpell effects — DC {5}\n{6}", "Wapen {0}% — {1}, AC {2}\nSpell attack {3}% — AC {4}\nSpell effects — DC {5}\n{6}"),
        ["NoGearEquipped"] = ("No gear equipped", "Geen uitrusting gedragen"),
        ["NoConditionalEffects"] = ("No conditional effects", "Geen voorwaardelijke effecten"),
        ["NoCriticalHits"] = ("critical-hit immune", "immuun voor critical hits"),
        ["AcCalculation"] = ("AC calculation: {0}", "AC-berekening: {0}"),
        ["SpellDcCalculation"] = ("Spell Save DC calculation: {0}", "Spell Save DC-berekening: {0}"),
        ["CriticalCalculation"] = ("Critical-hit calculation", "Critical-hitberekening"),
        ["CalculationBaseEight"] = ("8 base", "8 basis"),
        ["CalculationProficiency"] = ("{0} proficiency", "{0} proficiency"),
        ["CalculationAbilityModifier"] = ("{0} {1} modifier: {2}", "{0} {1}-modifier: {2}"),
        ["AcUnarmoured"] = ("10 base {0} DEX", "10 basis {0} DEX"),
        ["AcMageArmour"] = ("13 Mage Armour {0} DEX", "13 Mage Armour {0} DEX"),
        ["AcBarbarian"] = ("10 Unarmoured Defence {0} DEX {1} CON", "10 Unarmoured Defence {0} DEX {1} CON"),
        ["AcMonk"] = ("10 Unarmoured Defence {0} DEX {1} WIS", "10 Unarmoured Defence {0} DEX {1} WIS"),
        ["AcArmourBase"] = ("{0}: {1} base AC", "{0}: {1} basis-AC"),
        ["AcArmourDexBase"] = ("{0}: {1} base AC {2} DEX", "{0}: {1} basis-AC {2} DEX"),
        ["AcBarkskinMinimum"] = ("Barkskin raises {0} to its minimum of 16", "Barkskin verhoogt {0} tot het minimum van 16"),
        ["CriticalBase"] = ("20 base threshold", "20 basisdrempel"),
        ["CriticalSpellSniper"] = ("- 1  Spell Sniper (spell attacks only)", "- 1  Spell Sniper (alleen spell attacks)"),
        ["CriticalWeaponResult"] = ("Weapon attacks: {0}+ = {1}% per roll", "Wapenaanvallen: {0}+ = {1}% per worp"),
        ["CriticalSpellResult"] = ("Spell attacks: {0}+ = {1}% per roll", "Spell attacks: {0}+ = {1}% per worp"),
        ["CriticalNaturalOne"] = ("Natural 1 always misses; reductions stack and are not capped at 14.", "Een natuurlijke 1 mist altijd; verlagingen stapelen en zijn niet begrensd op 14."),
        ["DamageReduction"] = ("damage reduction {0}", "damage reduction {0}"),
        ["TemporaryHitPoints"] = ("{0} temporary HP after Long Rest", "{0} tijdelijke HP na Long Rest"),
        ["Resistances"] = ("resistance: {0}", "resistance: {0}"),
        ["NonProficientGear"] = ("not proficient: {0} (attack rolls and saves: DIS; spellcasting blocked)", "niet proficient: {0} (attack rolls en saves: DIS; spellcasting geblokkeerd)")
        , ["UnmetRequirements"] = ("{0} unmet requirement(s)", "{0} onvervulde voorwaarde(n)")
        , ["UnmetRequirementsTitle"] = ("INACTIVE / UNMET CONDITIONS", "INACTIEF / ONVERVULDE VOORWAARDEN")
        , ["AllRequirementsMet"] = ("All selected effects meet their currently modelled conditions.", "Alle geselecteerde effecten voldoen aan hun gemodelleerde voorwaarden.")
    };

    public static string T(string key) =>
        Texts.TryGetValue(key, out var value)
            ? Current == UiLanguage.English ? value.English : value.Dutch
            : key;

    public static string Format(string key, params object[] values) => string.Format(T(key), values);
}
